// src/comp/AppComp.tsx
import * as React from 'react'
import { connect } from 'react-redux'
import { loadGameThunk } from '../action/loadGameThunk'
import { newGameThunk } from '../action/newGameThunk'
import { savedGameExists } from '../fun/savedGameExists'
import { IAppState } from '../model/AppState'
import { TBag } from '../model/Bag'
import { BINGO_SCORE } from '../model/Constants'
import { Mode } from '../model/Mode'
import { selectIsBingo } from '../select/selectIsBingo'
import { selectBag, selectMode } from '../select/simpleSelectors'
import './AppComp.css'
import { BagComp } from './BagComp'
import { BoardComp } from './BoardComp'
import { DispatchProp } from './DispatchProp'
import { ErrorsComp } from './ErrorsComp'
import { GameEndedComp } from './GameEndedComp'
import { HandComp } from './HandComp'
import { OwnWordInfoComp } from './OwnWordInfoComp'
import { PlacedWordInfoComp } from './PlacedWordInfoComp'
import { PlaceTileButtonsComp } from './PlaceTileButtonsComp'
import { PlayersComp } from './PlayersComp'
import { ReplaceTilesButtonsComp } from './ReplaceTilesButtonsComp'

interface IAppCompPropsFromState {
	mode: Mode
	bag: TBag
	isBingo: boolean
}
export interface IAppCompProps extends IAppCompPropsFromState, DispatchProp {}

export const AppComp = connect(
	(state: IAppState): IAppCompPropsFromState => ({
		mode: selectMode(state),
		bag: selectBag(state),
		isBingo: selectIsBingo(state),
	}),
)(({ mode, bag, isBingo, dispatch }: IAppCompProps) => {
	return (
		<>
			<BoardComp />
			<div className='tools'>
				{mode === Mode.NotStarted && (
					<>
						{savedGameExists() && (
							<button
								onClick={e => {
									dispatch(loadGameThunk())
								}}
							>{`Folytatás`}</button>
						)}
						<button
							onClick={e => {
								dispatch(newGameThunk())
							}}
						>{`Új játék`}</button>
					</>
				)}
				{mode === Mode.PlaceTile && (
					<>
						<PlayersComp isEnabled />
						<BagComp bag={bag} />
						<HandComp />
						{isBingo && (
							<div className='bingo'>{`+${BINGO_SCORE} pont!`}</div>
						)}
						<OwnWordInfoComp />
						<ErrorsComp />
						<PlaceTileButtonsComp />
						<PlacedWordInfoComp />
					</>
				)}
				{mode === Mode.ReplaceTiles && (
					<>
						<HandComp />
						<ReplaceTilesButtonsComp />
					</>
				)}
				{mode === Mode.Ended && <GameEndedComp />}
			</div>
		</>
	)
})

// src/comp/AppComp.vue
<script setup lang="ts">
import { savedGameExists } from '@/fun/savedGameExists'
import { Mode } from '../model/Mode'
import { useStore } from '../store/useStore'
import BoardComp from './BoardComp.vue'
import PlayersComp from './PlayersComp.vue'
import HandComp from './HandComp.vue'
import OwnWordInfoComp from './OwnWordInfoComp.vue'
import ErrorsComp from './ErrorsComp.vue'
import { BINGO_SCORE } from '@/model/Constants'
import PlaceTileButtonsComp from './PlaceTileButtonsComp.vue'
import PlacedWordInfoComp from './PlacedWordInfoComp.vue'
import { useQueryClient } from '@tanstack/vue-query'
import ReplaceTilesButtonsComp from './ReplaceTilesButtonsComp.vue'
import GameEndedComp from './GameEndedComp.vue'
import ButtonsComp from './ButtonsComp.vue'
import { ref } from 'vue'
import SetJokerLetterComp from './SetJokerLetterComp.vue'

const store = useStore()

const queryClient = useQueryClient()
queryClient.setQueryDefaults([], {
	staleTime: Infinity,
	refetchOnMount: false,
	refetchOnWindowFocus: false,
	refetchOnReconnect: false,
	cacheTime: Infinity,
})

const showSetJokerLetter = ref(false)
</script>

<template>
	<BoardComp @setJokerLetter="showSetJokerLetter = true" />
	<div class="tools">
		<ButtonsComp v-if="store.mode === Mode.NotStarted">
			<button v-if="savedGameExists()" @click="store.loadGame">
				▶️ Folytatás</button
			><button @click="store.newGame">⭐ Új játék</button>
		</ButtonsComp>
		<template v-else-if="store.mode === Mode.PlaceTile">
			<PlayersComp />

			<HandComp />
			<div v-if="store.isBingo" class="bingo">+{{ BINGO_SCORE }} pont!</div>
			<OwnWordInfoComp />
			<ErrorsComp />
			<PlaceTileButtonsComp @setJokerLetter="showSetJokerLetter = true" />
			<PlacedWordInfoComp />
		</template>
		<template v-else-if="store.mode === Mode.ReplaceTiles">
			<HandComp />
			<ReplaceTilesButtonsComp />
		</template>
		<GameEndedComp v-else-if="store.mode === Mode.Ended" />
	</div>
	<SetJokerLetterComp
		:isOpen="showSetJokerLetter"
		@close="showSetJokerLetter = false"
	/>
</template>

<style scoped>
.tools {
	flex: 0 1 100%;
}

.bingo {
	padding: 8vmin 2vmin;
	font-size: 1.5rem;
	color: hotpink;
	text-align: center;
}
</style>
