// src/comp/PlacedWordInfoComp.tsx
import { connect } from 'react-redux'
import { IAppState } from '../model/AppState'
import { IValidAndInvalidWords } from '../model/IValidAndInvalidWords'
import { selectPlacedValidAndInvalidWords } from '../select/selectPlacedValidAndInvalidWords'
import { DispatchProp } from './DispatchProp'
import './PlacedWordInfoComp.css'
import { WordListComp } from './WordListComp'

export interface PlacedWordInfoCompPropsFromStore {
	words: IValidAndInvalidWords | null
}
export interface PlacedWordInfoCompProps
	extends PlacedWordInfoCompPropsFromStore,
		DispatchProp {}

export const PlacedWordInfoComp = connect(
	(state: IAppState): PlacedWordInfoCompPropsFromStore => ({
		words: selectPlacedValidAndInvalidWords(state),
	}),
)(({ words, dispatch }: PlacedWordInfoCompProps) => {
	return (
		<>
			{words && (
				<div className='placed-word-info'>
					<WordListComp
						words={words.valid}
						label={`Szavak a választott mezőn`}
					/>
				</div>
			)}
		</>
	)
})

// src/comp/PlacedWordInfoComp.vue
<script setup lang="ts">
import { useStore } from '@/store/useStore'
import WordListComp from './WordListComp.vue'

const store = useStore()
</script>

<template>
	<div v-if="!!store.placedValidAndInvalidWords" className="placed-word-info">
		<WordListComp :words="store.placedValidAndInvalidWords.valid"
			><template v-slot:label>Szavak a választott mezőn</template></WordListComp
		>
	</div>
</template>

<style scoped>
.placed-word-info {
	padding: 1vmin;
}
</style>
