// src/comp/PlaceTileButtonsComp.tsx
import { get } from 'illa/FunctionUtil'
import { connect } from 'react-redux'
import { collectTiles, setJokerLetter, setMode } from '../action/actions'
import { doneThunk } from '../action/doneThunk'
import { newGameThunk } from '../action/newGameThunk'
import { skipThunk } from '../action/skipThunk'
import { getPotentialWords } from '../fun/getPotentialWords'
import { hasError } from '../fun/hasError'
import { isLoaded } from '../fun/isLoaded'
import { isLoading } from '../fun/isLoading'
import { needsLoading } from '../fun/needsLoading'
import { IAppState } from '../model/AppState'
import { TBag } from '../model/Bag'
import { TBoard } from '../model/Board'
import { Direction } from '../model/Direction'
import { THand } from '../model/Hands'
import { IWordsValidity } from '../model/IWordsValidity'
import { Mode } from '../model/Mode'
import { MoveError } from '../model/MoveError'
import { TLoadable } from '../model/TLoadable'
import letters from '../res/letters.json'
import { selectHand } from '../select/selectHand'
import { selectMoveErrors } from '../select/selectMoveErrors'
import { selectMoveScore } from '../select/selectMoveScore'
import {
	selectBag,
	selectBoard,
	selectWordsValidity,
} from '../select/simpleSelectors'
import { DispatchProp } from './DispatchProp'
import './PlaceTileButtonsComp.css'

interface PlaceTileButtonsCompPropsFromStore {
	board: TBoard
	fieldIndex: number | null
	bag: TBag
	moveScore: number
	moveErrors: MoveError[]
	hand: THand | null
	wordsValidity: TLoadable<IWordsValidity>
}
export interface PlaceTileButtonsCompProps
	extends PlaceTileButtonsCompPropsFromStore,
		DispatchProp {}

export const PlaceTileButtonsComp = connect(
	(state: IAppState): PlaceTileButtonsCompPropsFromStore => ({
		bag: selectBag(state),
		board: selectBoard(state),
		fieldIndex: state.fieldIndex,
		moveScore: selectMoveScore(state),
		moveErrors: selectMoveErrors(state),
		hand: selectHand(state),
		wordsValidity: selectWordsValidity(state),
	}),
)(
	({
		board,
		fieldIndex,
		bag,
		moveScore,
		moveErrors,
		hand,
		wordsValidity,
		dispatch,
	}: PlaceTileButtonsCompProps) => {
		return (
			<div className='buttons'>
				<button
					disabled={
						moveErrors.length > 0 ||
						!isLoaded(wordsValidity) ||
						wordsValidity.loaded.invalidWords.length > 0
					}
					onClick={(e) => {
						dispatch(doneThunk())
					}}
				>
					{isLoading(wordsValidity) && `...`}
					{hasError(wordsValidity) && `Hiba!`}
					{(needsLoading(wordsValidity) || isLoaded(wordsValidity)) && `Oké`}
					{moveScore > 0 && (
						<>
							{`: `}
							<small>
								{moveScore}
								{` `}
								{`pont`}
							</small>
						</>
					)}
				</button>
				<button
					onClick={(e) => {
						dispatch(collectTiles())
					}}
				>
					{`Szedd össze`}
				</button>
				<button
					disabled={bag.length < 7}
					onClick={(e) => {
						dispatch(collectTiles())
						dispatch(setMode(Mode.ReplaceTiles))
					}}
				>
					{`Csere`}
				</button>
				<button
					onClick={(e) => {
						if (window.confirm(`Biztos hogy nem teszel semmit?`)) {
							dispatch(skipThunk())
						}
					}}
				>
					{`Kihagyom`}
				</button>
				<button
					onClick={(e) => {
						if (window.confirm(`Biztos hogy új játékot akarsz kezdeni?`)) {
							dispatch(newGameThunk())
						}
					}}
				>
					{`Új játék`}
				</button>
				{hand != null && (
					<button
						onClick={(e) => {
							alert(
								`Vízszintes: ${
									getPotentialWords({
										board,
										direction: Direction.Horizontal,
										hand,
									})
										.map((_) => _.word)
										.join(', ') || '–'
								}\nFüggőleges: ${
									getPotentialWords({
										board,
										direction: Direction.Vertical,
										hand,
									})
										.map((_) => _.word)
										.join(', ') || '–'
								}`,
							)
						}}
					>
						{`Tipp`}
					</button>
				)}
				{((tile) => tile && tile.isJoker && tile.isOwned)(
					get(() => board[fieldIndex!].tile),
				) && (
					<select
						value={board[fieldIndex!].tile!.letter}
						onChange={(e) => {
							dispatch(setJokerLetter({ letter: e.target.value }))
						}}
					>
						{letters.map((letter, index) => (
							<option key={index}>{letter.letter}</option>
						))}
					</select>
				)}
			</div>
		)
	},
)

// src/comp/PlaceTileButtonsComp.vue
<script setup lang="ts">
import { loadWordsValidity } from '@/fun/loadWordsValidity'
import { Mode } from '@/model/Mode'
import { QueryKey } from '@/model/QueryKey'
import { useStore } from '@/store/useStore'
import { useQuery } from '@tanstack/vue-query'
import { computed, ref } from 'vue'
import ButtonsComp from './ButtonsComp.vue'
import HintsComp from './HintsComp.vue'

defineEmits(['setJokerLetter'])

const store = useStore()

const queryKey = computed(() => [
	QueryKey.AreWordsValid,
	store.allOwnedWordStrings,
])
function queryFn() {
	return loadWordsValidity(store.allOwnedWordStrings)
}
const {
	data: validity,
	isLoading,
	isError,
} = useQuery({
	queryKey: queryKey,
	queryFn: queryFn,
})

const okButtonDisabled = computed(() => {
	return (
		store.moveErrors.length > 0 ||
		isLoading.value ||
		isError.value ||
		validity.value!.invalidWords.length > 0
	)
})
const okButtonLabel = computed(() => {
	if (isLoading.value) return '⌚'
	if (isError.value) return '❌ Hiba!'
	return '✅ Oké'
})
const isJoker = computed(
	() => !!(store.tile && store.tile.isJoker && store.tile.isOwned),
)

function swapTiles() {
	store.collectTiles()
	store.setMode(Mode.ReplaceTiles)
}

function skip() {
	if (window.confirm(`Biztos hogy nem teszel semmit?`)) {
		store.skip()
	}
}

function newGame() {
	if (window.confirm(`Biztos hogy új játékot akarsz kezdeni?`)) {
		store.newGame()
	}
}

const hintsAreOpen = ref(false)

function showHints() {
	store.collectTiles()
	hintsAreOpen.value = true
}
</script>

<template>
	<ButtonsComp>
		<button :disabled="okButtonDisabled">
			{{ okButtonLabel
			}}<span v-if="store.moveScore > 0" class="score"
				>: {{ store.moveScore }}&nbsp;pont</span
			></button
		><button @click="store.collectTiles">⏏ Szedd össze</button
		><button :disabled="store.bag.length < 7" @click="swapTiles">
			🔄&nbsp;Csere</button
		><button @click="skip">💁‍♀️ Kihagyom</button
		><button @click="newGame">⭐ Új játék</button
		><button v-if="store.hand" @click="showHints">🪄 Tipp</button
		><button
			v-if="store.tile?.isOwned && store.tile.isJoker"
			@click="$emit('setJokerLetter')"
		>
			✍️ Átírom a lapka betűjét</button
		><HintsComp :isOpen="hintsAreOpen" @close="hintsAreOpen = false" />
	</ButtonsComp>
</template>

<style scoped></style>
